# Generated by Django 5.1.5 on 2026-01-06 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del ejercicio')),
                ('exercise_type', models.CharField(blank=True, choices=[('walking_outside', 'Caminar exterior'), ('walking_treadmill', 'Caminar cinta'), ('cycling_outside', 'Bicicleta exterior'), ('cycling_treadmill', 'Bicicleta cinta'), ('elliptical_treadmill', 'Elíptica cinta')], max_length=255, null=True, verbose_name='Tipo de ejercicio')),
                ('session_start', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de inicio')),
                ('session_end', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de fin')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación')),
                ('workout_time', models.DurationField(blank=True, null=True, verbose_name='Duración del entrenamiento')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Distancia (km)')),
                ('avg_speed', models.FloatField(blank=True, null=True, verbose_name='Velocidad promedio (km/h)')),
                ('active_calories', models.IntegerField(blank=True, null=True, verbose_name='Calorías activas (kcal)')),
                ('total_calories', models.IntegerField(blank=True, null=True, verbose_name='Calorías totales (kcal)')),
                ('elevation_gain', models.IntegerField(blank=True, null=True, verbose_name='Ganancia de elevación (m)')),
                ('average_heart_rate', models.IntegerField(blank=True, null=True, verbose_name='Frecuencia cardíaca promedio (bpm)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardio_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sesión de cardio',
                'verbose_name_plural': 'Sesiones de cardio',
                'ordering': ['-date', '-session_start'],
            },
        ),
    ]
