"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-vz+du974h9+nba#ix&ggwst-sqs8cgsd%@1txg^sht#d_^fmlt"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Unfold django theme
    "unfold",
    "crispy_forms",
    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Project apps
    "evolveme",
    "cardio",
    "nutrition",
    "gym",
    "ia.apps.IaConfig",
    # Project commands
    "project_commands",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "project" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "django_db",
        "USER": "postgres",
        "PASSWORD": "postgres",
        "HOST": "postgres",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Evolveme
ADMIN_USERNAME = os.getenv("ADMIN_USERNAME", "")
ADMIN_PASSWORD = os.getenv("ADMIN_PASSWORD", "")
ADMIN_EMAIL = os.getenv("ADMIN_EMAIL", "")

ADMIN_GROUPS = os.getenv("ADMIN_GROUPS", "").split(",")
ROLE_PERMISSIONS = {
    "owner": [
        # Carme
        {
            "app_label": "carme",
            "model": "event",
            "permissions": ["add", "view", "change", "delete"],
        },
        {
            "app_label": "carme",
            "model": "reminder",
            "permissions": ["add", "view", "change", "delete"],
        },
        # Evolveme
        {
            "app_label": "evolveme",
            "model": "gymuserprofile",
            "permissions": ["add", "view", "change", "delete"],
        },
        {
            "app_label": "evolveme",
            "model": "cardio",
            "permissions": ["add", "view", "change", "delete"],
        },
        {
            "app_label": "evolveme",
            "model": "musculationexercise",
            "permissions": ["add", "view", "change", "delete"],
        },
        {
            "app_label": "evolveme",
            "model": "trainingsession",
            "permissions": ["add", "view", "change", "delete"],
        },
        {
            "app_label": "evolveme",
            "model": "diet",
            "permissions": ["add", "view", "change", "delete"],
        },
        {
            "app_label": "evolveme",
            "model": "measure",
            "permissions": ["add", "view", "change", "delete"],
        },
        {
            "app_label": "evolveme",
            "model": "routine",
            "permissions": ["add", "view", "change", "delete"],
        },
        {
            "app_label": "evolveme",
            "model": "dietgenerator",
            "permissions": ["add", "view", "change", "delete"],
        },
        # Finme
        {
            "app_label": "finme",
            "model": "movement",
            "permissions": ["add", "view", "change", "delete"],
        },
        {
            "app_label": "finme",
            "model": "balance",
            "permissions": ["add", "view", "change", "delete"],
        },
    ],
    # Client groups
    "client": [
        # Carme
        {
            "app_label": "carme",
            "model": "event",
            "permissions": ["add", "view", "change", "delete"],
        },
        {
            "app_label": "carme",
            "model": "reminder",
            "permissions": ["view"],
        },
        # Evolveme
        {
            "app_label": "evolveme",
            "model": "gymuserprofile",
            "permissions": ["view"],
        },
        {
            "app_label": "evolveme",
            "model": "cardio",
            "permissions": ["add", "view", "change", "delete"],
        },
        {
            "app_label": "evolveme",
            "model": "musculationexercise",
            "permissions": ["view"],
        },
        {
            "app_label": "evolveme",
            "model": "trainingsession",
            "permissions": ["add", "view", "change", "delete"],
        },
        {
            "app_label": "evolveme",
            "model": "diet",
            "permissions": ["view"],
        },
        {
            "app_label": "evolveme",
            "model": "measure",
            "permissions": ["add", "view", "change", "delete"],
        },
        {
            "app_label": "evolveme",
            "model": "routine",
            "permissions": ["view"],
        },
        {
            "app_label": "evolveme",
            "model": "dietgenerator",
            "permissions": ["view"],
        },
        # Finme
        {
            "app_label": "finme",
            "model": "movement",
            "permissions": ["add", "view", "change", "delete"],
        },
        {
            "app_label": "finme",
            "model": "balance",
            "permissions": ["view"],
        },
    ],
}

CRISPY_ALLOWED_TEMPLATE_PACKS = ["unfold_crispy"]
CRISPY_TEMPLATE_PACK = "unfold_crispy"

# Unfold Configuration
UNFOLD = {
    "SITE_TITLE": "EvolveMe",
    "SITE_HEADER": "EvolveMe",
    "SITE_SUBHEADER": "Panel de Administración",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: "/static/ico_dark.png",  # Icono oscuro en tema claro
        "dark": lambda request: "/static/ico_light.png",  # Icono claro en tema oscuro
    },
    "SITE_LOGO": {
        "light": lambda request: "/static/ico_dark.png",  # Logo oscuro en tema claro
        "dark": lambda request: "/static/ico_light.png",  # Logo claro en tema oscuro
    },
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/png",
            "href": lambda request: "/static/ico_dark.png",  # Icono oscuro para tema claro
        },
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/png",
            "href": lambda request: "/static/ico_light.png",  # Icono claro para tema oscuro
            "media": "(prefers-color-scheme: dark)",
        },
    ],
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_BACK_BUTTON": False,
    "BORDER_RADIUS": "8px",
    "THEME": None,  # Permite cambio de tema (claro/oscuro)
    "STYLES": [
        "/static/css/unfold_custom.css",
    ],
    "COLORS": {
        "base": {
            # Grises oscuros - basado en #2b2b2b (gris oscuro) y #212121 (gris muy oscuro)
            # Modo claro: colores un poco más oscuros que blanco perfecto
            "50": "oklch(95% 0 0)",  # Gris muy claro (no blanco perfecto)
            "100": "oklch(88% 0 0)",  # Gris claro
            "200": "oklch(75% 0 0)",  # Gris medio-claro
            "300": "oklch(60% 0 0)",  # Gris medio
            "400": "oklch(50% 0 0)",  # Gris medio-oscuro
            "500": "oklch(40% 0 0)",  # Gris oscuro (#2b2b2b aproximado)
            "600": "oklch(35% 0 0)",  # Gris más oscuro
            "700": "oklch(30% 0 0)",  # Gris muy oscuro (#212121 aproximado)
            "800": "oklch(25% 0 0)",  # Gris casi negro
            "900": "oklch(20% 0 0)",  # Gris negro
            "950": "oklch(15% 0 0)",  # Negro
        },
        "primary": {
            # Amarillo - basado en #ba9e00
            "50": "oklch(95% 0.05 90)",  # Amarillo muy claro
            "100": "oklch(90% 0.08 90)",  # Amarillo claro
            "200": "oklch(85% 0.10 90)",  # Amarillo medio-claro
            "300": "oklch(80% 0.12 90)",  # Amarillo medio
            "400": "oklch(75% 0.14 90)",  # Amarillo
            "500": "oklch(70% 0.15 90)",  # Amarillo principal (#ba9e00 aproximado)
            "600": "oklch(65% 0.15 90)",  # Amarillo oscuro
            "700": "oklch(60% 0.14 90)",  # Amarillo más oscuro
            "800": "oklch(55% 0.12 90)",  # Amarillo muy oscuro
            "900": "oklch(50% 0.10 90)",  # Amarillo casi negro
            "950": "oklch(45% 0.08 90)",  # Amarillo negro
        },
        "font": {
            "subtle-light": "var(--color-base-500)",
            "subtle-dark": "var(--color-base-400)",
            "default-light": "var(--color-base-600)",
            "default-dark": "var(--color-base-300)",
            "important-light": "var(--color-base-900)",
            "important-dark": "var(--color-base-100)",
        },
    },
}
