"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-vz+du974h9+nba#ix&ggwst-sqs8cgsd%@1txg^sht#d_^fmlt"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Unfold django theme
    "unfold",
    "crispy_forms",
    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Project apps
    "evolveme",
    # Project commands
    "project_commands",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "django_db",
        "USER": "postgres",
        "PASSWORD": "postgres",
        "HOST": "postgres",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Evolveme
ADMIN_USERNAME = os.getenv("ADMIN_USERNAME", "")
ADMIN_PASSWORD = os.getenv("ADMIN_PASSWORD", "")
ADMIN_EMAIL = os.getenv("ADMIN_EMAIL", "")

ADMIN_GROUPS = os.getenv("ADMIN_GROUPS", "").split(",")
ROLE_PERMISSIONS = {
    "owner": [
        # Carme
        {
            "app_label": "carme",
            "model": "event",
            "permissions": ["add", "view", "change", "delete"],
        },
        {
            "app_label": "carme",
            "model": "reminder",
            "permissions": ["add", "view", "change", "delete"],
        },
        # Evolveme
        {
            "app_label": "evolveme",
            "model": "gymuserprofile",
            "permissions": ["add", "view", "change", "delete"],
        },
        {
            "app_label": "evolveme",
            "model": "cardio",
            "permissions": ["add", "view", "change", "delete"],
        },
        {
            "app_label": "evolveme",
            "model": "musculationexercise",
            "permissions": ["add", "view", "change", "delete"],
        },
        {
            "app_label": "evolveme",
            "model": "trainingsession",
            "permissions": ["add", "view", "change", "delete"],
        },
        {
            "app_label": "evolveme",
            "model": "diet",
            "permissions": ["add", "view", "change", "delete"],
        },
        {
            "app_label": "evolveme",
            "model": "measure",
            "permissions": ["add", "view", "change", "delete"],
        },
        {
            "app_label": "evolveme",
            "model": "routine",
            "permissions": ["add", "view", "change", "delete"],
        },
        {
            "app_label": "evolveme",
            "model": "dietgenerator",
            "permissions": ["add", "view", "change", "delete"],
        },
        # Finme
        {
            "app_label": "finme",
            "model": "movement",
            "permissions": ["add", "view", "change", "delete"],
        },
        {
            "app_label": "finme",
            "model": "balance",
            "permissions": ["add", "view", "change", "delete"],
        },
    ],
    # Client groups
    "client": [
        # Carme
        {
            "app_label": "carme",
            "model": "event",
            "permissions": ["add", "view", "change", "delete"],
        },
        {
            "app_label": "carme",
            "model": "reminder",
            "permissions": ["view"],
        },
        # Evolveme
        {
            "app_label": "evolveme",
            "model": "gymuserprofile",
            "permissions": ["view"],
        },
        {
            "app_label": "evolveme",
            "model": "cardio",
            "permissions": ["add", "view", "change", "delete"],
        },
        {
            "app_label": "evolveme",
            "model": "musculationexercise",
            "permissions": ["view"],
        },
        {
            "app_label": "evolveme",
            "model": "trainingsession",
            "permissions": ["add", "view", "change", "delete"],
        },
        {
            "app_label": "evolveme",
            "model": "diet",
            "permissions": ["view"],
        },
        {
            "app_label": "evolveme",
            "model": "measure",
            "permissions": ["add", "view", "change", "delete"],
        },
        {
            "app_label": "evolveme",
            "model": "routine",
            "permissions": ["view"],
        },
        {
            "app_label": "evolveme",
            "model": "dietgenerator",
            "permissions": ["view"],
        },
        # Finme
        {
            "app_label": "finme",
            "model": "movement",
            "permissions": ["add", "view", "change", "delete"],
        },
        {
            "app_label": "finme",
            "model": "balance",
            "permissions": ["view"],
        },
    ],
}

CRISPY_ALLOWED_TEMPLATE_PACKS = ["unfold_crispy"]
CRISPY_TEMPLATE_PACK = "unfold_crispy"
