# Generated by Django 5.2.13 on 2026-05-04 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(null=True, verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10, null=True, verbose_name='Género')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Altura (cm)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('objective', models.CharField(blank=True, choices=[('lose_weight', 'Perder peso'), ('gain_muscle', 'Ganar músculo'), ('gain_weight', 'Ganar peso'), ('improve_health', 'Mejorar la salud'), ('improve_performance', 'Mejorar el rendimiento')], max_length=255, null=True, verbose_name='Objetivo')),
                ('active_routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_routine', to='gym.routine', verbose_name='Rutina activa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Información del usuario',
                'verbose_name_plural': 'Información de los usuarios',
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Peso (kg)')),
                ('arm', models.FloatField(blank=True, help_text='Brazo flexionado - Flexiona bíceps a 90°, mide punto más grueso (fitness/progreso muscular)', null=True, verbose_name='Brazo (cm)')),
                ('arm_relaxed', models.FloatField(blank=True, help_text='Brazo relajado - Punto medio entre hombro-codo, brazo colgando relajado (antropometría médica/nutricional)', null=True, verbose_name='Brazo relajado (cm)')),
                ('chest', models.FloatField(blank=True, null=True, verbose_name='Pecho (cm)')),
                ('waist', models.FloatField(blank=True, null=True, verbose_name='Cintura (cm)')),
                ('leg', models.FloatField(blank=True, help_text='Pierna flexionada - Flexiona cuádriceps, mide muslo más ancho (fitness/progreso muscular)', null=True, verbose_name='Pierna (cm)')),
                ('leg_relaxed', models.FloatField(blank=True, help_text='Pierna relajada - Sin tensión (antropometría médica/nutricional)', null=True, verbose_name='Pierna relajada (cm)')),
                ('fat_perc', models.FloatField(blank=True, null=True, verbose_name='Porcentaje de masa grasa (%)')),
                ('muscle_mass', models.FloatField(blank=True, null=True, verbose_name='Masa muscular (kg)')),
                ('bmi', models.FloatField(blank=True, null=True, verbose_name='Índice de masa corporal (BMI)')),
                ('body_water_mass', models.FloatField(blank=True, null=True, verbose_name='Masa de agua corporal (kg)')),
                ('body_water_percentage', models.FloatField(blank=True, null=True, verbose_name='Porcentaje de agua corporal (%)')),
                ('fat_mass', models.FloatField(blank=True, null=True, verbose_name='Masa grasa (kg)')),
                ('bone_mineral_content', models.FloatField(blank=True, null=True, verbose_name='Contenido mineral óseo (kg)')),
                ('bone_mineral_percentage', models.FloatField(blank=True, null=True, verbose_name='Porcentaje de mineral óseo (%)')),
                ('protein_mass', models.FloatField(blank=True, null=True, verbose_name='Masa proteica (kg)')),
                ('protein_percentage', models.FloatField(blank=True, null=True, verbose_name='Porcentaje de proteína (%)')),
                ('muscle_percentage', models.FloatField(blank=True, null=True, verbose_name='Porcentaje muscular (%)')),
                ('skeletal_muscle_mass', models.FloatField(blank=True, null=True, verbose_name='Masa muscular esquelética (kg)')),
                ('visceral_fat_rating', models.FloatField(blank=True, null=True, verbose_name='Calificación de grasa visceral')),
                ('basal_metabolic_rate', models.FloatField(blank=True, null=True, verbose_name='Tasa metabólica basal (Kcal)')),
                ('waist_to_hip_ratio', models.FloatField(blank=True, null=True, verbose_name='Ratio cintura-cadera')),
                ('body_age', models.IntegerField(blank=True, null=True, verbose_name='Edad corporal (años)')),
                ('fat_free_body_weight', models.FloatField(blank=True, null=True, verbose_name='Peso corporal libre de grasa (kg)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Medida',
                'verbose_name_plural': 'Medidas',
            },
        ),
        migrations.CreateModel(
            name='MeasureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evolveme/measures/%Y/%m/', verbose_name='Imagen')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='evolveme.measure', verbose_name='Medida')),
            ],
            options={
                'verbose_name': 'Imagen de medida',
                'verbose_name_plural': 'Imágenes de medida',
            },
        ),
    ]
