# Generated by Django 5.1.5 on 2026-01-06 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(null=True, verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10, null=True, verbose_name='Género')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Altura (cm)')),
                ('objective', models.CharField(blank=True, choices=[('lose_weight', 'Perder peso'), ('gain_muscle', 'Ganar músculo'), ('gain_weight', 'Ganar peso'), ('improve_health', 'Mejorar la salud'), ('improve_performance', 'Mejorar el rendimiento')], max_length=255, null=True, verbose_name='Objetivo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Información del usuario',
                'verbose_name_plural': 'Información de los usuarios',
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Peso (kg)')),
                ('arm', models.FloatField(blank=True, null=True, verbose_name='Brazo (cm)')),
                ('chest', models.FloatField(blank=True, null=True, verbose_name='Pecho (cm)')),
                ('waist', models.FloatField(blank=True, null=True, verbose_name='Cintura (cm)')),
                ('leg', models.FloatField(blank=True, null=True, verbose_name='Pierna (cm)')),
                ('fat_perc', models.FloatField(blank=True, null=True, verbose_name='Porcentaje de masa grasa (Kg)')),
                ('muscle_mass', models.FloatField(blank=True, null=True, verbose_name='Masa muscular (Kg)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Medida',
                'verbose_name_plural': 'Medidas',
            },
        ),
    ]
