# Generated by Django 5.1.5 on 2025-07-01 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('walking_outside', 'Caminar exterior'), ('walking_treadmill', 'Caminar cinta'), ('cycling_outside', 'Bicicleta exterior'), ('cycling_treadmill', 'Bicicleta cinta'), ('elliptical_treadmill', 'Elíptica cinta')], max_length=255, verbose_name='Tipo de actividad')),
                ('workout_time', models.IntegerField(verbose_name='Duración (min)')),
                ('distance', models.FloatField(verbose_name='Distancia (km)')),
                ('active_calories', models.IntegerField(verbose_name='Calorías activas')),
                ('total_calories', models.IntegerField(verbose_name='Calorías totales')),
                ('elevation_gain', models.IntegerField(verbose_name='Elevación (m)')),
                ('average_heart_rate', models.IntegerField(verbose_name='Frecuencia cardíaca promedio (bpm)')),
                ('avg_speed', models.FloatField(verbose_name='Velocidad promedio (km/h)')),
            ],
            options={
                'verbose_name': 'Actividad de cardio',
                'verbose_name_plural': 'Actividades de cardio',
            },
        ),
        migrations.CreateModel(
            name='MusculationExercise',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID del ejercicio')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del ejercicio')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('body_part', models.CharField(blank=True, choices=[('chest', 'Pecho'), ('back', 'Espalda'), ('legs', 'Piernas'), ('arms', 'Brazos'), ('shoulders', 'Hombros'), ('abs', 'Abdomen')], max_length=255, null=True, verbose_name='Parte del cuerpo')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('image_base64', models.TextField(blank=True, null=True, verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Ejercicio de musculación',
                'verbose_name_plural': 'Ejercicios de musculación',
            },
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('meal_type', models.CharField(blank=True, choices=[('breakfast', 'Desayuno'), ('lunch', 'Almuerzo'), ('snack', 'Snack'), ('dinner', 'Cena'), ('nibble', 'Picoteo')], max_length=255, null=True, verbose_name='Tipo de comida')),
                ('food', models.TextField(blank=True, null=True, verbose_name='Comida')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('calories', models.IntegerField(blank=True, null=True, verbose_name='Calorías (kcal)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Dieta',
                'verbose_name_plural': 'Dietas',
            },
        ),
        migrations.CreateModel(
            name='GymUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(null=True, verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10, null=True, verbose_name='Género')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Altura (cm)')),
                ('objective', models.CharField(blank=True, choices=[('lose_weight', 'Perder peso'), ('gain_muscle', 'Ganar músculo'), ('gain_weight', 'Ganar peso'), ('improve_health', 'Mejorar la salud'), ('improve_performance', 'Mejorar el rendimiento')], max_length=255, null=True, verbose_name='Objetivo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Información del usuario',
                'verbose_name_plural': 'Información de los usuarios',
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Peso (kg)')),
                ('arm', models.FloatField(blank=True, null=True, verbose_name='Brazo (cm)')),
                ('chest', models.FloatField(blank=True, null=True, verbose_name='Pecho (cm)')),
                ('waist', models.FloatField(blank=True, null=True, verbose_name='Cintura (cm)')),
                ('leg', models.FloatField(blank=True, null=True, verbose_name='Pierna (cm)')),
                ('fat_perc', models.FloatField(blank=True, null=True, verbose_name='Porcentaje de masa grasa (Kg)')),
                ('muscle_mass', models.FloatField(blank=True, null=True, verbose_name='Masa muscular (Kg)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Medida',
                'verbose_name_plural': 'Medidas',
            },
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(verbose_name='Peso (kg)')),
                ('reps', models.IntegerField(verbose_name='Repeticiones')),
                ('sets', models.IntegerField(verbose_name='Series')),
                ('tbi', models.BooleanField(verbose_name='To be improved')),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evolveme.musculationexercise', verbose_name='Ejercicio')),
            ],
            options={
                'verbose_name': 'Set de ejercicio',
                'verbose_name_plural': 'Sets de ejercicios',
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la rutina')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin')),
                ('exercises', models.ManyToManyField(to='evolveme.musculationexercise', verbose_name='Ejercicios')),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('cardio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evolveme.cardioexercise', verbose_name='Actividad de cardio')),
                ('musculation', models.ManyToManyField(blank=True, to='evolveme.exerciseset', verbose_name='Ejercicios de musculación')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sesión de entrenamiento',
                'verbose_name_plural': 'Sesiones de entrenamiento',
            },
        ),
    ]
