# Generated by Django 5.2.13 on 2026-04-08 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evolveme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evolveme/measures/%Y/%m/', verbose_name='Imagen')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='evolveme.measure', verbose_name='Medida')),
            ],
            options={
                'verbose_name': 'Imagen de medida',
                'verbose_name_plural': 'Imágenes de medida',
            },
        ),
    ]
