# Generated by Django 5.1.5 on 2026-01-17 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evolveme', '0001_initial'),
        ('gym', '0002_routine_exercise_types_routine_warmup'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymuserprofile',
            name='active_routine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_routine', to='gym.routine', verbose_name='Rutina activa'),
        ),
    ]
