# Generated by Django 5.1.5 on 2026-01-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evolveme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='basal_metabolic_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Tasa metabólica basal (Kcal)'),
        ),
        migrations.AddField(
            model_name='measure',
            name='bmi',
            field=models.FloatField(blank=True, null=True, verbose_name='Índice de masa corporal (BMI)'),
        ),
        migrations.AddField(
            model_name='measure',
            name='body_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad corporal (años)'),
        ),
        migrations.AddField(
            model_name='measure',
            name='body_water_mass',
            field=models.FloatField(blank=True, null=True, verbose_name='Masa de agua corporal (kg)'),
        ),
        migrations.AddField(
            model_name='measure',
            name='body_water_percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='Porcentaje de agua corporal (%)'),
        ),
        migrations.AddField(
            model_name='measure',
            name='bone_mineral_content',
            field=models.FloatField(blank=True, null=True, verbose_name='Contenido mineral óseo (kg)'),
        ),
        migrations.AddField(
            model_name='measure',
            name='bone_mineral_percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='Porcentaje de mineral óseo (%)'),
        ),
        migrations.AddField(
            model_name='measure',
            name='fat_free_body_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso corporal libre de grasa (kg)'),
        ),
        migrations.AddField(
            model_name='measure',
            name='fat_mass',
            field=models.FloatField(blank=True, null=True, verbose_name='Masa grasa (kg)'),
        ),
        migrations.AddField(
            model_name='measure',
            name='muscle_percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='Porcentaje muscular (%)'),
        ),
        migrations.AddField(
            model_name='measure',
            name='protein_mass',
            field=models.FloatField(blank=True, null=True, verbose_name='Masa proteica (kg)'),
        ),
        migrations.AddField(
            model_name='measure',
            name='protein_percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='Porcentaje de proteína (%)'),
        ),
        migrations.AddField(
            model_name='measure',
            name='skeletal_muscle_mass',
            field=models.FloatField(blank=True, null=True, verbose_name='Masa muscular esquelética (kg)'),
        ),
        migrations.AddField(
            model_name='measure',
            name='visceral_fat_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Calificación de grasa visceral'),
        ),
        migrations.AddField(
            model_name='measure',
            name='waist_to_hip_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='Ratio cintura-cadera'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='fat_perc',
            field=models.FloatField(blank=True, null=True, verbose_name='Porcentaje de masa grasa (%)'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='muscle_mass',
            field=models.FloatField(blank=True, null=True, verbose_name='Masa muscular (kg)'),
        ),
    ]
