# Generated by Django 5.1.5 on 2026-01-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evolveme', '0002_gymuserprofile_active_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymuserprofile',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AddField(
            model_name='gymuserprofile',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
    ]
