# Generated by Django 5.2.13 on 2026-05-04 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymLLMResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(verbose_name='Respuesta')),
                ('stored', models.BooleanField(default=False, verbose_name='Almacenado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Respuesta del modelo',
                'verbose_name_plural': 'Respuestas del modelo',
            },
        ),
        migrations.CreateModel(
            name='LLMClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('url', models.URLField(verbose_name='URL')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente de LLM',
                'verbose_name_plural': 'Clientes de LLM',
            },
        ),
        migrations.CreateModel(
            name='NutritionLLMResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(verbose_name='Respuesta')),
                ('stored', models.BooleanField(default=False, verbose_name='Almacenado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Respuesta del modelo',
                'verbose_name_plural': 'Respuestas del modelo',
            },
        ),
        migrations.CreateModel(
            name='OllamaServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField(help_text='URL base del servidor Ollama, p.ej. http://localhost:11434')),
                ('enabled', models.BooleanField(default=True)),
                ('api_key', models.CharField(blank=True, help_text='Opcional, por si el servidor requiere API key', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servidor Ollama',
                'verbose_name_plural': 'Servidores Ollama',
            },
        ),
        migrations.CreateModel(
            name='ProductLLMResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.JSONField(verbose_name='Productos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Respuesta del modelo',
                'verbose_name_plural': 'Respuestas del modelo',
            },
        ),
        migrations.CreateModel(
            name='Promtps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('prompt', models.TextField(verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prompt',
                'verbose_name_plural': 'Prompts',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_key', models.CharField(blank=True, help_text="Clave del modelo usado, p.ej. 'local|llama3.1:8b-q4_K_M'", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de chat',
                'verbose_name_plural': 'Sesiones de chat',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ia.chatsession')),
            ],
            options={
                'verbose_name': 'Mensaje de chat',
                'verbose_name_plural': 'Mensajes de chat',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OllamaModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text="Nombre tal y como lo expone Ollama (ej. 'llama3', 'qwen2.5', etc.)", max_length=100)),
                ('temperature', models.FloatField(default=0.7)),
                ('top_p', models.FloatField(default=0.9)),
                ('max_tokens', models.PositiveIntegerField(default=512)),
                ('alias', models.CharField(help_text="Nombre lógico en la app (p.ej. 'asistente_pronosticos')", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='Si es el modelo por defecto para este servidor/uso')),
                ('deprecated', models.BooleanField(default=False, help_text='Marcar como deprecado (no recomendado para uso nuevo).')),
                ('deprecated_at', models.DateTimeField(blank=True, help_text='Fecha de deprecación (opcional).', null=True)),
                ('proposito', models.CharField(blank=True, help_text="Uso del modelo (p. ej. 'OCR', 'Razonamiento del nutricionista', 'Chat').", max_length=255, verbose_name='Propósito')),
                ('downloaded', models.BooleanField(default=False, help_text='Si el modelo está actualmente descargado en el servidor Ollama.', verbose_name='Descargado')),
                ('digest', models.CharField(blank=True, help_text='Digest del modelo en Ollama (para detectar actualizaciones).', max_length=64, verbose_name='Digest')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Última comprobación')),
                ('update_available', models.BooleanField(default=False, help_text='Hay una versión nueva disponible o el modelo no está descargado.', verbose_name='Actualización disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='ia.ollamaserver')),
            ],
            options={
                'verbose_name': 'Modelo Ollama',
                'verbose_name_plural': 'Modelos Ollama',
                'unique_together': {('server', 'model_name')},
            },
        ),
    ]
