# Generated by Django 5.1.5 on 2026-01-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('url', models.URLField(verbose_name='URL')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente de LLM',
                'verbose_name_plural': 'Clientes de LLM',
            },
        ),
        migrations.CreateModel(
            name='ProductLLMResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.JSONField(verbose_name='Productos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Respuesta del modelo',
                'verbose_name_plural': 'Respuestas del modelo',
            },
        ),
        migrations.RenameModel(
            old_name='ModelGymResponse',
            new_name='GymLLMResponse',
        ),
        migrations.RenameModel(
            old_name='ModelNutritionResponse',
            new_name='NutritionLLMResponse',
        ),
    ]
