# Generated by Django 5.1.5 on 2026-03-04 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OllamaServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField(help_text='URL base del servidor Ollama, p.ej. http://localhost:11434')),
                ('enabled', models.BooleanField(default=True)),
                ('api_key', models.CharField(blank=True, help_text='Opcional, por si el servidor requiere API key', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servidor Ollama',
                'verbose_name_plural': 'Servidores Ollama',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_key', models.CharField(blank=True, help_text="Clave del modelo usado, p.ej. 'local|llama3.1:8b-q4_K_M'", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de chat',
                'verbose_name_plural': 'Sesiones de chat',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ia.chatsession')),
            ],
            options={
                'verbose_name': 'Mensaje de chat',
                'verbose_name_plural': 'Mensajes de chat',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OllamaModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text="Nombre tal y como lo expone Ollama (ej. 'llama3', 'qwen2.5', etc.)", max_length=100)),
                ('temperature', models.FloatField(default=0.7)),
                ('top_p', models.FloatField(default=0.9)),
                ('max_tokens', models.PositiveIntegerField(default=512)),
                ('alias', models.CharField(help_text="Nombre lógico en la app (p.ej. 'asistente_pronosticos')", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='Si es el modelo por defecto para este servidor/uso')),
                ('deprecated', models.BooleanField(default=False, help_text='Marcar como deprecado (no recomendado para uso nuevo).')),
                ('deprecated_at', models.DateTimeField(blank=True, help_text='Fecha de deprecación (opcional).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='ia.ollamaserver')),
            ],
            options={
                'verbose_name': 'Modelo Ollama',
                'verbose_name_plural': 'Modelos Ollama',
                'unique_together': {('server', 'model_name')},
            },
        ),
    ]
