# Generated by Django 5.2.13 on 2026-05-04 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Outdoor Walk', 'Caminar exterior'), ('Indoor Walk', 'Caminar cinta'), ('Outdoor Cycle', 'Bicicleta exterior'), ('Indoor Cycle', 'Bicicleta estática'), ('Elliptical', 'Elíptica'), ('Musculation', 'Musculación')], max_length=255, verbose_name='Nombre del ejercicio')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('image_base64', models.TextField(blank=True, null=True, verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Ejercicio de cardio',
                'verbose_name_plural': 'Ejercicios de cardio',
            },
        ),
        migrations.CreateModel(
            name='MusculationExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del ejercicio')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('body_part', models.CharField(blank=True, choices=[('chest', 'Pecho'), ('back', 'Espalda'), ('legs', 'Piernas'), ('arms', 'Brazos'), ('shoulders', 'Hombros'), ('abs', 'Abdomen'), ('forearms', 'Antebrazos'), ('core', 'Zona media')], max_length=255, null=True, verbose_name='Parte del cuerpo')),
                ('sets', models.IntegerField(verbose_name='Series')),
                ('reps', models.IntegerField(verbose_name='Repeticiones')),
                ('unit', models.CharField(choices=[('reps', 'Repeticiones'), ('seconds', 'Segundos')], max_length=255, verbose_name='Unidad')),
                ('image_base64', models.TextField(blank=True, null=True, verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Ejercicio de musculación',
                'verbose_name_plural': 'Ejercicios de musculación',
            },
        ),
        migrations.CreateModel(
            name='CardioSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de inicio')),
                ('session_end', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de fin')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación')),
                ('workout_time', models.DurationField(blank=True, null=True, verbose_name='Duración del entrenamiento')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Distancia (km)')),
                ('avg_speed', models.FloatField(blank=True, null=True, verbose_name='Velocidad promedio (km/h)')),
                ('active_calories', models.IntegerField(blank=True, null=True, verbose_name='Calorías activas (kcal)')),
                ('total_calories', models.IntegerField(blank=True, null=True, verbose_name='Calorías totales (kcal)')),
                ('elevation_gain', models.IntegerField(blank=True, null=True, verbose_name='Ganancia de elevación (m)')),
                ('average_heart_rate', models.IntegerField(blank=True, null=True, verbose_name='Frecuencia cardíaca promedio (bpm)')),
                ('workout_image', models.ImageField(blank=True, help_text='Opcional. Sube una captura o foto del entrenamiento para extraer datos con IA.', null=True, upload_to='cardio/%Y/%m/', verbose_name='Imagen del entrenamiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='gym.cardioexercise', verbose_name='Ejercicio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardio_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sesión de cardio',
                'verbose_name_plural': 'Sesiones de cardio',
                'ordering': ['-date', '-session_start'],
            },
        ),
        migrations.CreateModel(
            name='MusculationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(verbose_name='Series')),
                ('reps', models.IntegerField(verbose_name='Repeticiones')),
                ('weight', models.IntegerField(verbose_name='Peso (kg)')),
                ('tbi', models.BooleanField(verbose_name='To be improved')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('record_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de registro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='gym.musculationexercise', verbose_name='Ejercicio')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musculation_records', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de ejercicio de musculación',
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_types', models.JSONField(blank=True, default=list, help_text='Múltiples selecciones de tipos de ejercicios', null=True, verbose_name='Tipos de ejercicios')),
                ('warmup_duration', models.DurationField(blank=True, null=True, verbose_name='Duración de calentamiento')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duración de la rutina en semanas', null=True, verbose_name='Duración de la rutina (semanas)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercises', models.ManyToManyField(related_name='routines', to='gym.musculationexercise', verbose_name='Ejercicios')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('warmup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='gym.cardioexercise', verbose_name='Ejercicio de calentamiento')),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de la sesión')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación')),
                ('workout_time', models.DurationField(blank=True, null=True, verbose_name='Duración de la sesión')),
                ('active_kilocalories', models.IntegerField(blank=True, null=True, verbose_name='Kcal activas')),
                ('total_kilocalories', models.IntegerField(blank=True, null=True, verbose_name='Kcal totales')),
                ('avg_heart_rate', models.IntegerField(blank=True, null=True, verbose_name='FC media (BPM)')),
                ('workout_image', models.ImageField(blank=True, help_text='Opcional. Sube una captura o foto del entrenamiento para extraer datos con IA.', null=True, upload_to='gym/%Y/%m/', verbose_name='Imagen del entrenamiento')),
                ('routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='gym.routine', verbose_name='Rutina')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sesión de entrenamiento',
                'verbose_name_plural': 'Sesiones de entrenamiento',
            },
        ),
    ]
