# Generated by Django 5.1.5 on 2026-01-05 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusculationExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del ejercicio')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('body_part', models.CharField(blank=True, choices=[('chest', 'Pecho'), ('back', 'Espalda'), ('legs', 'Piernas'), ('arms', 'Brazos'), ('shoulders', 'Hombros'), ('abs', 'Abdomen'), ('forearms', 'Antebrazos'), ('core', 'Zona media')], max_length=255, null=True, verbose_name='Parte del cuerpo')),
                ('image_base64', models.TextField(blank=True, null=True, verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Ejercicio de musculación',
                'verbose_name_plural': 'Ejercicios de musculación',
            },
        ),
        migrations.CreateModel(
            name='MusculationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(verbose_name='Series')),
                ('reps', models.IntegerField(verbose_name='Repeticiones')),
                ('weight', models.IntegerField(verbose_name='Peso (kg)')),
                ('tbi', models.BooleanField(verbose_name='To be improved')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('record_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de registro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.musculationexercise', verbose_name='Ejercicio')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de ejercicio de musculación',
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Exercises', models.ManyToManyField(to='gym.musculationexercise', verbose_name='Ejercicios')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de la sesión')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación')),
                ('workout_time', models.DurationField(blank=True, null=True, verbose_name='Duración de la sesión')),
                ('active_kilocalories', models.IntegerField(blank=True, null=True, verbose_name='Kcal activas')),
                ('total_kilocalories', models.IntegerField(blank=True, null=True, verbose_name='Kcal totales')),
                ('avg_heart_rate', models.IntegerField(blank=True, null=True, verbose_name='FC media (BPM)')),
                ('routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.routine', verbose_name='Rutina')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sesión de entrenamiento',
                'verbose_name_plural': 'Sesiones de entrenamiento',
            },
        ),
    ]
