# Generated by Django 5.1.5 on 2026-01-25 19:49
# Modified: interval cannot be cast to integer in PostgreSQL; use add → migrate → remove → rename

from django.db import migrations, models


def duration_interval_to_weeks(apps, schema_editor):
    """Convierte duración interval a semanas (entero). Si había valor, aproximamos días/7."""
    Routine = apps.get_model("gym", "Routine")
    for r in Routine.objects.all():
        old_val = getattr(r, "duration_old", None)
        if old_val is not None:
            total_seconds = old_val.total_seconds()
            r.duration_weeks = max(1, int(round(total_seconds / (7 * 24 * 3600))))
        else:
            r.duration_weeks = None
        r.save()


def reverse_duration_weeks_to_interval(apps, schema_editor):
    """Revierte: semanas (entero) a interval (para rollback)."""
    from datetime import timedelta

    Routine = apps.get_model("gym", "Routine")
    for r in Routine.objects.all():
        weeks = getattr(r, "duration_weeks", None)
        if weeks is not None:
            setattr(r, "duration_old", timedelta(weeks=weeks))
        else:
            setattr(r, "duration_old", None)
        r.save()


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0001_initial"),
    ]

    operations = [
        # 1. Añadir nuevo campo entero (nombre temporal para no chocar con el existente)
        migrations.AddField(
            model_name="routine",
            name="duration_weeks",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Duración de la rutina en semanas",
                null=True,
                verbose_name="Duración de la rutina (semanas)",
            ),
        ),
        # 2. Renombrar el campo antiguo para poder migrar datos
        migrations.RenameField(
            model_name="routine",
            old_name="duration",
            new_name="duration_old",
        ),
        # 3. Migrar datos: interval -> semanas (aproximado)
        migrations.RunPython(duration_interval_to_weeks, reverse_duration_weeks_to_interval),
        # 4. Eliminar el campo antiguo (interval)
        migrations.RemoveField(
            model_name="routine",
            name="duration_old",
        ),
        # 5. Renombrar duration_weeks -> duration
        migrations.RenameField(
            model_name="routine",
            old_name="duration_weeks",
            new_name="duration",
        ),
    ]
