# Generated by Django 5.1.5 on 2026-01-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='exercise_types',
            field=models.JSONField(blank=True, default=list, help_text="Lista de tipos de ejercicios: ['push', 'pull', 'legs', 'core', 'full_body', 'lower_body', 'upper_body', 'abs', 'forearms']", null=True, verbose_name='Tipos de ejercicios'),
        ),
        migrations.AddField(
            model_name='routine',
            name='warmup',
            field=models.TextField(blank=True, null=True, verbose_name='Calentamiento'),
        ),
    ]
