# Generated by Django 5.1.5 on 2026-01-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duración de la rutina en semanas', null=True, verbose_name='Duración de la rutina (semanas)'),
        ),
    ]
