# Generated by Django 5.1.5 on 2026-01-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_add_sets_reps_to_musculationexercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musculationexercise',
            name='reps',
            field=models.IntegerField(verbose_name='Repeticiones'),
        ),
        migrations.AlterField(
            model_name='musculationexercise',
            name='sets',
            field=models.IntegerField(verbose_name='Series'),
        ),
    ]
