# Generated by Django 5.1.5 on 2026-01-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_routine_exercise_types_routine_warmup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='exercise_types',
            field=models.JSONField(blank=True, default=list, help_text='Múltiples selecciones de tipos de ejercicios', null=True, verbose_name='Tipos de ejercicios'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
    ]
