# Generated by Django 5.1.5 on 2026-01-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_alter_routine_end_date_alter_routine_exercise_types_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routine',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rutina', 'verbose_name_plural': 'Rutinas'},
        ),
        migrations.RemoveField(
            model_name='routine',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='start_date',
        ),
        migrations.AddField(
            model_name='routine',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Duración de la rutina'),
        ),
    ]
