# Generated by Django 5.1.5 on 2026-01-05 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('market', models.CharField(blank=True, choices=[('mercadona', 'Mercadona'), ('carrefour', 'Carrefour'), ('lidl', 'Lidl'), ('alcampo', 'Alcampo'), ('other', 'Otro')], max_length=255, verbose_name='Mercado')),
                ('calories_per_100g', models.FloatField(default=0, verbose_name='Calorías por 100g')),
                ('protein_per_100g', models.FloatField(default=0, verbose_name='Proteínas por 100g (g)')),
                ('carbs_per_100g', models.FloatField(default=0, verbose_name='Carbohidratos por 100g (g)')),
                ('fat_per_100g', models.FloatField(default=0, verbose_name='Grasas por 100g (g)')),
                ('saturated_fat_per_100g', models.FloatField(blank=True, default=0, null=True, verbose_name='Grasas saturadas por 100g (g)')),
                ('monounsaturated_fat_per_100g', models.FloatField(blank=True, default=0, null=True, verbose_name='Grasas monoinsaturadas por 100g (g)')),
                ('polyunsaturated_fat_per_100g', models.FloatField(blank=True, default=0, null=True, verbose_name='Grasas poliinsaturadas por 100g (g)')),
                ('sugars_per_100g', models.FloatField(blank=True, default=0, null=True, verbose_name='Azúcares por 100g (g)')),
                ('polyols_per_100g', models.FloatField(blank=True, default=0, null=True, verbose_name='Polialcoholes por 100g (g)')),
                ('fiber_per_100g', models.FloatField(blank=True, default=0, null=True, verbose_name='Fibra alimentaria por 100g (g)')),
                ('salt_per_100g', models.FloatField(blank=True, default=0, null=True, verbose_name='Sal por 100g (g)')),
                ('stock', models.CharField(choices=[('yes', 'SI'), ('no', 'NO'), ('buy', 'Comprar')], default='no', max_length=10, verbose_name='Stock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='DailyDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Usuario al que se asigna la dieta (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Dieta diaria',
                'verbose_name_plural': 'Dietas diarias',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MealMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.FloatField(default=0, verbose_name='Calorías')),
                ('protein', models.FloatField(default=0, verbose_name='Proteínas')),
                ('carbs', models.FloatField(default=0, verbose_name='Carbohidratos')),
                ('fat', models.FloatField(default=0, verbose_name='Grasas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.dailydiet', verbose_name='Dieta diaria')),
            ],
            options={
                'verbose_name': 'Métricas de comida',
                'verbose_name_plural': 'Métricas de comida',
            },
        ),
        migrations.CreateModel(
            name='ProductQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0, verbose_name='Cantidad')),
                ('unit', models.CharField(blank=True, max_length=255, verbose_name='Unidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Cantidad de producto',
                'verbose_name_plural': 'Cantidades de productos',
            },
        ),
        migrations.AddField(
            model_name='dailydiet',
            name='products',
            field=models.ManyToManyField(to='food.productquantity', verbose_name='Productos y cantidad ingerida'),
        ),
    ]
