# Generated by Django 5.1.5 on 2026-01-05 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='food_products',
        ),
    ]
